export enum ImporterType {
  CHARLES = "CHARLES",
  RESOURCE_OVERRIDE = "RESOURCE_OVERRIDE",
  MOD_HEADER = "MOD_HEADER",
  REQUESTLY = "REQUESTLY",
  HEADER_EDITOR = "HEADER_EDITOR",
  FILES = "FILES",
}
